CREATE TABLE India_Sales(
   SaleId   VARCHAR(7) NOT NULL PRIMARY KEY
  ,Category VARCHAR(13) NOT NULL
  ,Product  VARCHAR(24) NOT NULL
  ,Qty      NUMERIC(4,1)
  ,Sale     INTEGER  NOT NULL
);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0001','Perfumes','Park Avenue Perfumes',8.0,972);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0002','Jeans','Lee Jeans',3.0,895);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0003','Shoes','Woodland Shoes',9.0,616);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0004','Water bottles','Kinley Water bottles',8.0,1005);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0005','Jeans','Pepe Jeans Jeans',2.0,653);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0006','Perfumes','Denver Perfumes',2.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0007','Perfumes','AXE Perfumes',7.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0008','Perfumes','AXE Perfumes',8.0,936);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0009','Perfumes','Wild Stone Perfumes',8.0,936);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0010','Smart Phone','Samsung Smart Phone',5.0,968);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0011','Water bottles','Tupperware Water bottles',6.0,544);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0012','Water bottles','Tupperware Water bottles',5.0,905);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0013','Perfumes','Denver Perfumes',2.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0014','Shoes','Bata Shoes',6.0,616);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0015','Jeans','Lee Jeans',6.0,653);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0016','Tshirts','Adidas Tshirt',9.0,1167);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0017','Tshirts','Peter England Tshirt',9.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0018','Perfumes','Park Avenue Perfumes',7.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0019','Jeans','Levi''s Jeans',1.0,567);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0020','Smart Phone','Samsung Smart Phone',2.0,644);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0021','Jeans','Wrangler Jeans',NULL,653);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0022','Jeans','Levi''s Jeans',2.0,752);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0023','Smart Phone','Vivo Smart Phone',5.0,1063);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0024','Water bottles','Aquafina Water bottles',3.0,1005);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0025','Jeans','Mufti Jeans',5.0,1045);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0026','Tshirts','Nike Tshirt',10.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0027','Jeans','Levi''s Jeans',6.0,752);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0028','Perfumes','Fogg Perfumes',2.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0029','Water bottles','Milton Water bottles',2.0,699);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0030','Perfumes','AXE Perfumes',7.0,972);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0031','Shoes','Bata Shoes',2.0,1061);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0032','Perfumes','Park Avenue Perfumes',8.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0033','Perfumes','Park Avenue Perfumes',10.0,972);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0034','Tshirts','Adidas Tshirt',5.0,742);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0035','Smart Phone','Vivo Smart Phone',6.0,644);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0036','Tshirts','Peter England Tshirt',9.0,1167);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0037','Water bottles','Cello Water bottles',1.0,699);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0038','Tshirts','Puma Tshirt',5.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0039','Jeans','Lee Jeans',9.0,567);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0040','Shoes','Reebok Shoes',6.0,882);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0041','Jeans','Pepe Jeans Jeans',4.0,839);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0042','Jeans','Levi''s Jeans',9.0,895);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0043','Tshirts','Puma Tshirt',8.0,923);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0044','Perfumes','Wild Stone Perfumes',3.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0045','Perfumes','Denver Perfumes',3.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0046','Shoes','Reebok Shoes',6.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0047','Smart Phone','Redmi Smart Phone',10.0,1050);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0048','Jeans','Levi''s Jeans',3.0,839);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0049','Water bottles','Kinley Water bottles',2.0,699);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0050','Tshirts','Zara Tshirt',8.0,742);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0051','Jeans','Pepe Jeans Jeans',8.0,839);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0052','Smart Phone','OnePlus Smart Phone',3.0,1063);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0053','Tshirts','Peter England Tshirt',6.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0054','Perfumes','Wild Stone Perfumes',2.0,972);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0055','Perfumes','Park Avenue Perfumes',10.0,936);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0056','Shoes','Nike Shoes',1.0,1061);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0057','Water bottles','Milton Water bottles',3.0,544);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0058','Jeans','Pepe Jeans Jeans',5.0,1045);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0059','Tshirts','Adidas Tshirt',1.0,1167);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0060','Perfumes','Wild Stone Perfumes',5.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0061','Shoes','Adidas Shoes',6.0,1162);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0062','Jeans','Lee Jeans',1.0,653);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0063','Smart Phone','Samsung Smart Phone',9.0,1050);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0064','Jeans','Levi''s Jeans',9.0,752);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0065','Smart Phone','Samsung Smart Phone',6.0,1050);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0066','Water bottles','Milton Water bottles',2.0,544);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0067','Shoes','Woodland Shoes',6.0,1061);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0068','Water bottles','Tupperware Water bottles',9.0,1005);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0069','Tshirts','Peter England Tshirt',4.0,1167);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0070','Jeans','Lee Jeans',4.0,895);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0071','Water bottles','Cello Water bottles',9.0,665);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0072','Smart Phone','Vivo Smart Phone',7.0,644);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0073','Smart Phone','Vivo Smart Phone',6.0,1056);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0074','Tshirts','Peter England Tshirt',7.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0075','Perfumes','Fogg Perfumes',2.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0076','Shoes','Nike Shoes',6.0,757);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0077','Perfumes','Wild Stone Perfumes',9.0,936);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0078','Shoes','Woodland Shoes',NULL,1162);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0079','Perfumes','Park Avenue Perfumes',8.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0080','Smart Phone','Samsung Smart Phone',8.0,1063);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0081','Tshirts','Adidas Tshirt',NULL,867);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0082','Perfumes','Wild Stone Perfumes',4.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0083','Water bottles','Aquafina Water bottles',8.0,905);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0084','Water bottles','Kinley Water bottles',NULL,648);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0085','Smart Phone','OnePlus Smart Phone',6.0,1056);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0086','Shoes','Nike Shoes',9.0,616);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0087','Smart Phone','Vivo Smart Phone',5.0,1063);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0088','Shoes','Bata Shoes',2.0,1061);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0089','Shoes','Nike Shoes',10.0,1162);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0090','Jeans','Levi''s Jeans',7.0,839);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0091','Perfumes','AXE Perfumes',6.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0092','Smart Phone','Samsung Smart Phone',9.0,1050);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0093','Water bottles','Aquafina Water bottles',7.0,1005);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0094','Jeans','Lee Jeans',3.0,839);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0095','Perfumes','Park Avenue Perfumes',2.0,1098);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0096','Smart Phone','iPhone Smart Phone',NULL,1056);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0097','Jeans','Wrangler Jeans',8.0,839);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0098','Shoes','Reebok Shoes',9.0,1061);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0099','Tshirts','Puma Tshirt',6.0,867);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0100','Smart Phone','Redmi Smart Phone',3.0,830);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0101','Jeans','Wrangler Jeans',9.0,567);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0102','Smart Phone','Redmi Smart Phone',3.0,644);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0103','Smart Phone','Samsung Smart Phone',2.0,1050);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0104','Jeans','Levi''s Jeans',2.0,752);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0105','Perfumes','Wild Stone Perfumes',7.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0106','Tshirts','Puma Tshirt',3.0,923);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0107','Water bottles','Tupperware Water bottles',8.0,699);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0108','Water bottles','Kinley Water bottles',8.0,544);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0109','Smart Phone','iPhone Smart Phone',NULL,1056);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0110','Perfumes','Fogg Perfumes',3.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0111','Smart Phone','iPhone Smart Phone',8.0,830);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0112','Water bottles','Kinley Water bottles',1.0,905);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0113','Perfumes','Denver Perfumes',6.0,972);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0114','Jeans','Levi''s Jeans',9.0,653);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0115','Shoes','Nike Shoes',8.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0116','Shoes','Reebok Shoes',5.0,616);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0117','Perfumes','Fogg Perfumes',8.0,1098);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0118','Smart Phone','Samsung Smart Phone',9.0,830);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0119','Jeans','Levi''s Jeans',2.0,752);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0120','Jeans','Mufti Jeans',10.0,1045);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0121','Shoes','Adidas Shoes',4.0,1162);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0122','Perfumes','Wild Stone Perfumes',4.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0123','Perfumes','AXE Perfumes',5.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0124','Water bottles','Milton Water bottles',2.0,905);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0125','Tshirts','Puma Tshirt',1.0,1167);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0126','Tshirts','Puma Tshirt',2.0,867);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0127','Water bottles','Cello Water bottles',7.0,648);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0128','Jeans','Levi''s Jeans',4.0,839);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0129','Jeans','Wrangler Jeans',1.0,1045);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0130','Water bottles','Tupperware Water bottles',3.0,905);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0131','Water bottles','Kinley Water bottles',7.0,1005);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0132','Shoes','Adidas Shoes',9.0,1061);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0133','Water bottles','Kinley Water bottles',10.0,544);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0134','Shoes','Bata Shoes',5.0,882);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0135','Water bottles','Aquafina Water bottles',6.0,665);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0136','Tshirts','Puma Tshirt',1.0,867);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0137','Jeans','Wrangler Jeans',10.0,567);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0138','Tshirts','Peter England Tshirt',10.0,742);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0139','Jeans','Mufti Jeans',9.0,567);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0140','Perfumes','AXE Perfumes',7.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0141','Perfumes','Fogg Perfumes',7.0,972);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0142','Smart Phone','OnePlus Smart Phone',3.0,644);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0143','Smart Phone','Samsung Smart Phone',6.0,1050);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0144','Jeans','Mufti Jeans',10.0,895);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0145','Shoes','Bata Shoes',3.0,882);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0146','Smart Phone','Vivo Smart Phone',10.0,1063);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0147','Perfumes','Denver Perfumes',5.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0148','Jeans','Lee Jeans',5.0,1045);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0149','Water bottles','Cello Water bottles',6.0,648);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0150','Shoes','Nike Shoes',2.0,882);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0151','Shoes','Reebok Shoes',6.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0152','Jeans','Mufti Jeans',4.0,653);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0153','Perfumes','Fogg Perfumes',7.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0154','Water bottles','Milton Water bottles',1.0,1005);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0155','Water bottles','Tupperware Water bottles',2.0,699);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0156','Tshirts','Peter England Tshirt',5.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0157','Water bottles','Tupperware Water bottles',9.0,648);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0158','Smart Phone','Vivo Smart Phone',10.0,968);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0159','Water bottles','Tupperware Water bottles',9.0,1005);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0160','Tshirts','Zara Tshirt',NULL,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0161','Perfumes','Fogg Perfumes',3.0,972);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0162','Shoes','Reebok Shoes',4.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0163','Shoes','Bata Shoes',7.0,1162);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0164','Tshirts','Peter England Tshirt',7.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0165','Shoes','Adidas Shoes',4.0,1162);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0166','Smart Phone','Redmi Smart Phone',5.0,644);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0167','Jeans','Lee Jeans',10.0,895);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0168','Shoes','Adidas Shoes',10.0,882);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0169','Shoes','Nike Shoes',2.0,757);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0170','Tshirts','Peter England Tshirt',1.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0171','Perfumes','AXE Perfumes',1.0,972);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0172','Perfumes','Park Avenue Perfumes',8.0,972);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0173','Tshirts','Nike Tshirt',1.0,742);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0174','Tshirts','Puma Tshirt',7.0,923);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0175','Tshirts','Adidas Tshirt',6.0,867);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0176','Smart Phone','Samsung Smart Phone',7.0,830);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0177','Perfumes','Fogg Perfumes',8.0,936);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0178','Perfumes','Wild Stone Perfumes',1.0,1098);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0179','Tshirts','Zara Tshirt',3.0,923);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0180','Tshirts','Adidas Tshirt',8.0,1167);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0181','Water bottles','Cello Water bottles',3.0,699);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0182','Smart Phone','Vivo Smart Phone',7.0,644);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0183','Jeans','Mufti Jeans',10.0,752);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0184','Jeans','Lee Jeans',3.0,752);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0185','Perfumes','Wild Stone Perfumes',7.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0186','Smart Phone','Samsung Smart Phone',9.0,968);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0187','Water bottles','Aquafina Water bottles',8.0,648);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0188','Shoes','Woodland Shoes',10.0,616);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0189','Smart Phone','Redmi Smart Phone',4.0,1050);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0190','Smart Phone','Vivo Smart Phone',3.0,1063);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0191','Tshirts','Adidas Tshirt',1.0,1167);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0192','Tshirts','Nike Tshirt',5.0,923);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0193','Shoes','Adidas Shoes',1.0,882);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0194','Smart Phone','iPhone Smart Phone',9.0,1056);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0195','Tshirts','Nike Tshirt',4.0,923);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0196','Jeans','Levi''s Jeans',5.0,567);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0197','Water bottles','Aquafina Water bottles',5.0,665);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0198','Tshirts','Peter England Tshirt',9.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0199','Smart Phone','Redmi Smart Phone',6.0,1050);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0200','Tshirts','Peter England Tshirt',NULL,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0201','Tshirts','Peter England Tshirt',8.0,867);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0202','Shoes','Nike Shoes',1.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0203','Water bottles','Tupperware Water bottles',6.0,1005);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0204','Smart Phone','Redmi Smart Phone',10.0,1063);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0205','Smart Phone','OnePlus Smart Phone',8.0,1056);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0206','Jeans','Levi''s Jeans',4.0,752);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0207','Tshirts','Zara Tshirt',2.0,867);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0208','Smart Phone','iPhone Smart Phone',6.0,1056);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0209','Shoes','Adidas Shoes',8.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0210','Shoes','Nike Shoes',5.0,1061);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0211','Tshirts','Peter England Tshirt',10.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0212','Water bottles','Kinley Water bottles',2.0,665);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0213','Water bottles','Tupperware Water bottles',1.0,1005);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0214','Jeans','Pepe Jeans Jeans',2.0,895);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0215','Tshirts','Adidas Tshirt',5.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0216','Tshirts','Puma Tshirt',1.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0217','Smart Phone','Redmi Smart Phone',7.0,968);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0218','Tshirts','Puma Tshirt',1.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0219','Smart Phone','iPhone Smart Phone',1.0,1056);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0220','Jeans','Wrangler Jeans',5.0,839);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0221','Shoes','Adidas Shoes',8.0,1061);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0222','Perfumes','Denver Perfumes',1.0,936);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0223','Perfumes','AXE Perfumes',7.0,936);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0224','Shoes','Nike Shoes',7.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0225','Perfumes','AXE Perfumes',1.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0226','Shoes','Adidas Shoes',10.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0227','Perfumes','Fogg Perfumes',5.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0228','Perfumes','Wild Stone Perfumes',NULL,936);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0229','Water bottles','Milton Water bottles',10.0,699);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0230','Jeans','Lee Jeans',4.0,653);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0231','Water bottles','Kinley Water bottles',9.0,1005);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0232','Tshirts','Zara Tshirt',10.0,867);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0233','Perfumes','AXE Perfumes',6.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0234','Smart Phone','Redmi Smart Phone',10.0,968);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0235','Jeans','Wrangler Jeans',2.0,567);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0236','Tshirts','Zara Tshirt',3.0,742);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0237','Perfumes','AXE Perfumes',9.0,972);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0238','Tshirts','Nike Tshirt',4.0,867);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0239','Shoes','Nike Shoes',4.0,616);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0240','Jeans','Mufti Jeans',8.0,895);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0241','Perfumes','Fogg Perfumes',2.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0242','Perfumes','Wild Stone Perfumes',5.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0243','Shoes','Bata Shoes',4.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0244','Shoes','Reebok Shoes',2.0,882);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0245','Perfumes','Fogg Perfumes',5.0,972);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0246','Shoes','Woodland Shoes',8.0,882);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0247','Tshirts','Zara Tshirt',4.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0248','Smart Phone','Redmi Smart Phone',5.0,644);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0249','Water bottles','Tupperware Water bottles',4.0,648);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0250','Perfumes','Park Avenue Perfumes',3.0,972);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0251','Tshirts','Puma Tshirt',5.0,923);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0252','Water bottles','Aquafina Water bottles',3.0,699);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0253','Water bottles','Kinley Water bottles',6.0,665);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0254','Smart Phone','Redmi Smart Phone',4.0,968);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0255','Water bottles','Milton Water bottles',2.0,1005);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0256','Smart Phone','Samsung Smart Phone',6.0,830);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0257','Smart Phone','iPhone Smart Phone',10.0,1056);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0258','Jeans','Mufti Jeans',4.0,839);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0259','Jeans','Pepe Jeans Jeans',1.0,752);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0260','Smart Phone','iPhone Smart Phone',5.0,644);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0261','Smart Phone','Samsung Smart Phone',6.0,644);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0262','Tshirts','Adidas Tshirt',4.0,867);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0263','Water bottles','Kinley Water bottles',NULL,665);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0264','Jeans','Wrangler Jeans',4.0,653);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0265','Perfumes','Wild Stone Perfumes',2.0,1098);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0266','Jeans','Pepe Jeans Jeans',10.0,653);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0267','Jeans','Wrangler Jeans',4.0,895);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0268','Water bottles','Cello Water bottles',5.0,665);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0269','Tshirts','Zara Tshirt',6.0,923);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0270','Tshirts','Puma Tshirt',10.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0271','Shoes','Bata Shoes',4.0,882);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0272','Perfumes','Wild Stone Perfumes',NULL,936);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0273','Jeans','Lee Jeans',5.0,1045);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0274','Tshirts','Peter England Tshirt',6.0,1068);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0275','Perfumes','Fogg Perfumes',8.0,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0276','Water bottles','Cello Water bottles',7.0,544);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0277','Shoes','Adidas Shoes',2.0,1061);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0278','Smart Phone','OnePlus Smart Phone',2.0,830);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0279','Water bottles','Tupperware Water bottles',8.0,1005);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0280','Jeans','Wrangler Jeans',9.0,752);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0281','Shoes','Nike Shoes',6.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0282','Shoes','Adidas Shoes',3.0,757);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0283','Water bottles','Cello Water bottles',10.0,905);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0284','Perfumes','AXE Perfumes',1.0,936);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0285','Smart Phone','OnePlus Smart Phone',NULL,1050);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0286','Shoes','Adidas Shoes',2.0,882);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0287','Jeans','Lee Jeans',1.0,567);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0288','Shoes','Adidas Shoes',3.0,1061);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0289','Perfumes','Park Avenue Perfumes',NULL,821);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0290','Jeans','Wrangler Jeans',4.0,895);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0291','Water bottles','Tupperware Water bottles',2.0,1005);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0292','Water bottles','Kinley Water bottles',4.0,1005);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0293','Shoes','Adidas Shoes',2.0,534);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0294','Water bottles','Milton Water bottles',3.0,544);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0295','Shoes','Reebok Shoes',10.0,1061);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0296','Tshirts','Zara Tshirt',6.0,742);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0297','Perfumes','Wild Stone Perfumes',5.0,972);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0298','Tshirts','Nike Tshirt',8.0,867);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0299','Tshirts','Peter England Tshirt',7.0,923);
INSERT INTO India_Sales(SaleId,Category,Product,Qty,Sale) VALUES ('IN-0300','Perfumes','AXE Perfumes',1.0,1098);
